### ISSUE TITLE
PUT and PATCH methods in the Readme.md have exactly the same description

### ISSUE THREAD

**Issue by subodhk01** [COPS-IITBHU/csoc-2020-task-1#9]
There is no difference stated between the PUT and PATCH methods.
<img width="941" alt="Screenshot 2020-04-26 at 19 17 17" src="https://user-images.githubusercontent.com/19875783/80309447-bc58e800-87f2-11ea-8d2a-e39d22bb66b7.png">

**Comment by nishantwrp** [comment]
That's because in this case they have the same functionality.
